<?php 

$lang = array();

// Home page
$lang['personal story title'] = "Personal information";
$lang['personal story'] = "My name is Jip de Kok, I have graduated from Maastricht University, the faculty of Science and Engineering resulting in a degree of Bachelor of Science in Liberal Arts and Sciences from the Maastricht Science Programme. During my academic career I have studied scientific programming, where I have mainly applied my programming knowledge in a biological context. Some examples are automated data extrapolation, processing and visualisation using HTML and JavaScript with the Openphacts API. In this application, biological data about a specific disease and a predefined disease-specific drug is extrapolated from various databases. These targets are then compared to identify overlapping targets between a disease and its drug. Finally, these targets are then visualised as a force-directed graph using the D3.js library. All in all, my main focus has been on software development and molecular biology.";

$lang['index title'] = "Home"; //homepagina in dutch
$lang['personal info title'] = "Personal info" ;
$lang['portfolio title'] = "portfolio" ;
$lang['contact title'] = "contact" ;

//Personal information page
$lang["personal info title"] = "Personal information";
$lang["personal info text"] = 'My name is Jip de Kok, I have graduated from Maastricht University, the faculty of Science and Engineering resulting in a degree of Bachelor of Science in Liberal Arts and Sciences from the Maastricht Science Programme. During my academic career I have studied scientific programming, where I have mainly applied my programming knowledge in a biological context. One example is automated data extrapolation, processing and visualisation using HTML and JavaScript with the Openphacts API. In this application, biological data about a specific disease and a predefined disease-specific drug is extrapolated from various databases. These targets are then compared to identify overlapping targets between a disease and its drug. Finally, these targets are then visualised as a force-directed graph using the D3.js library. All in all, my main focus has been on software development and molecular biology. <br><br>

Biology has always interested me, the high complexity and interconnectivity of the countless molecular pathways composing our body and keeping it in balance is fascinating to study and a great challenge to mathematically reproduce. During my study at the Maastricht Science Programme I have taken multiple courses regarding cell- and molecular biology. Additionally, I have applied this knowledge in practice in the labs of the Brightlands campus at Chemelot. As I had laid my foundation of biological knowledge, I saw the opportunity to combine my interest in biology with my passion of computer science. Hence, I started taking programming and maths courses in which I could frequently apply my biological knowledge.  <br><br>
Already at elementary school I was interested in computers, and then I don’t just mean video games. I was always trying to tweak my slow bulky laptop into a somewhat-less-slow laptop with a gorgeous third-party user interface. Indubitably, I usually ended up bricking my system, forcing me to completely wipe and reinstall my windows partition. However, I think this where my passion and knowledge about computers originated from. After, exploring many Linux distro’s and upgrading my laptop’s RAM I soon realised I had pushed my laptop to its absolute limits and I started saving up for a high-end pc. With this increase in performance, new hobbies arose. I started programming and modelling 3D objects. These hobbies have persisted until today and I have used and improved these skillsets during my academic career. 3D modelling came in handy for various visualisations that I have made during my academic career and programming allowed me to do a variety of complex data analysis tasks and also for visualisations of complex data as I always find it satisfying to have a visual end product. Currently, I have a wide variety of computer skillsets and would like to start specifying in a more specific field in which I can excel.  <br><br>
That’s enough about my academic background, here I’ll briefly talk about myself personally. Besides my passion for computers I love to go outside hiking, skiing, mountain-biking or any other sport really, as long as it’s not ice skating. From my 16th I have been a boy scout leader, where I lead a group of boys in the age range of 7-11. Moreover, I play Spanish guitar which comes in handy to play some campfire songs during summer camp, although I prefer to play some more classical music when not around the campfire. &ltp class="informalUndertone"&gt Last but not least, I like to go out with friends in my pursuit of happiness. &lt/p&gt';

$lang["my details"] = "Mijn gegevens";
$lang['name'] =					"<span class=\"bold\">Naam:</span>			Jip de Kok";
$lang['age'] =				"<span class=\"bold\">Geboortedatum:</span>		13/09/1996";
$lang['gender'] = 				"<span class=\"bold\">Gender:</span>		Male";
$lang['email'] =				"<span class=\"bold\">Email:</span>			jipdekok@hotmail.com";
$lang['linkedin'] =				"<span class=\"bold\">Linkedin:</span>		<a target='_blank' href='https://www.linkedin.com/in/jip-de-kok-2a027075/'>https://www.linkedin.com/in/jip-de-kok-2a027075/</a>";
$lang['github'] =				"<span class=\"bold\">Github:</span>		<a target='_blank' href='https://github.com/thejipsess'>https://github.com/thejipsess</a>";
$lang['highschool degree'] =	"<span class=\"bold\">Middelbare school:</span>	VWO diploma met een natuur/geneeskunde- & natuur/techniek profiel - Trevianum";
$lang['university degree'] =	"<span class=\"bold\">Universiteit:</span>	Graad van Bachelor of Science in Liberal Arts and Sciences - Maastricht Science Programme";
$lang['languages'] =			"<span class=\"bold\">Talen:</span>		<ul><li>Nederlands</li><li>Engels</li><li>Frans (niet vloeiend)</li><li>Duits (niet vloeiend)</li><li>Python</li><li>R</li><li>Java</li><li>JavaScript</li><li>C#</li><li>HTML</li><li>																			CSS</li><li>PHP</li><li>MATLAB</li></ul>";
$lang['certificate'] =			"<span class=\"bold\">Certificaat:</span>	Camebridge English Level 2 Certificate in ESOL International (								advanced)";
$lang['software'] =				"<span class=\"bold\">Software:</span>		<ul><li>Autodeks 3ds max & Mudbox</li><li>Unity 3D</li><li>Adobe After Effects, Photoshop & Illustrator</li><li>Microsoft Visual																		Studio, Word, Powerpoint& Excel</li><li>MATLAB</li>";


//Portfolio page
$lang['master thesis title'] = "Master Thesis";
$lang['master thesis text'] = "In my master thesis I tuned, trained and tested a multitude of supervised Machine Learning (ML) techniques to predict the probability of later development of various atopic conditions such as asthma and eczema using infant gut microbiome data. In other words we investigated if it was possible to predict which infants will develop atopic conditions before the age of 11 using gut microbiome data that was collected at an age of 1 month post partum. In addition to microbiome data, I also had clinical variables, including information about maternal and paternal atopy, environmental exposures, etc. I tested the predictive performance of the models using the microbiome and clinical data seperately, but also with the combination of the two feature sets. In order to fuse the two feature sets I tested O2PLS and DIABLO, which are both sustainable mid-level data fusion techniques. The ML techniques that were used are XGBoost, Random Forest, Sparse Partial Least Squares Discriminant Analysis, Support Vector Machine, and Logisitc Regression.<br><br>
	Due to a confiditentiality agreement I cannot share the thesis or any of the results. Nevertheless, I would like to show one type of visualisation that I created during my thesis. Do note however, that these results are purely fictional and do not reflect the real results from the thesis whatsoever.
	<br><br>
	";
$lang['master thesis graph description'] = "Figure 1: Radar chart of the predictive performance of multiple machine learning models. The colours represent different machine learning models as indicated in the legend. All metrics are shown on the scale of percentages. The mean log loss is shown as “1 – log loss” as it has been inverted, such that higher values correspond to a better model, just as all other metrics. Any mean log loss higher than one was capped at one such that in this figure they cannot go below zero.";

$lang['thesis title'] = "Bachelor Thesis";
$lang['thesis text'] = "This thesis aimed at the improvement of large multi-omics network visualisations by utilisation of virtual reality. Due to the increasing size of biological datasets, it is getting more challenging to properly visualise such datasets in 2D. Therefore, different approaches should be considered, like virtual reality. In this thesis, an interactive virtual reality network of multi-omics data was developed and compared to a pre-existing 2D network from the same dataset. Finally, the virtual reality visualisation was compared to the 2D visualisation through conducting a cross-over design study where participants had to test the visualisations and, subsequently, evaluate them with a Likert scale survey. Essentially, no significant differences were found between the two types of visualisations from the survey data. However, the feedback was generally positive indicating that virtual reality visualisation has the potential to serve as an appropriate way of visualising multi-omics data but should still be further developed and tested.<br><br>
	To see the VR visualisation in action, where a genetic network is explored using state of the art infrared hand-tracking technology (leap motion), play the video below:";

$lang['profielwerkstuk title'] = "Profielwerkstuk (higschool end project)";
$lang['profielwerkstuk text'] = "Final high school project (profielwerkstuk)<br><br>

At the end of my studies at Trevianum, my pre-university education, I did my final project on the visualisation of the paracetamol-induced changes in the respiratory chain in mitochondria of cultured human liver cells. I did so in collaboration with Jian Jiang from the department of Toxicogenomics at Maastricht University who, at the time, was doing her PhD on Mechanisms of Drug-Induced Liver Injury. The goal of this study was to research the hepatotoxicity of paracetamol (APAP) by analysing whole-genome gene expression data. Her study revealed that a dose of 10mM APAP results in an increase in Reactive Oxygen Species (ROS) formation and disrupts the assembly, stability and structural integrity of Electron Transport Chain (ETC) complexes. Ultimately, resulting in electron leakage into the cell, depleting the cell of ATP, thus, possibly inducing cell death. This is a very brief summary of the research and only a small proportion of the entire thesis, if you are interested and would like to read more, click here: <a target=\"_blank\" href=\"https://toxicogenomics-um.nl/research/apap-induced-liver-injury-dili\">Read More…</a>, or send me a message for a free pdf.<br><br>
As I heard about this research I saw an opportunity to visualise this in a 3D environment to visually explain the data. This was done, by first modelling all individual component like the phospholipids, inter-membrane proteins, ATP, proton (carriers) and so forth. Here, arguably the most challenging part was to shape the components because there is no actual proof of their appearance due their incredibly small size and the complexity of protein folding. Therefore, most models were based on their appearance in scientific schematics, and a little bit of artistic freedom. However, for the phospholipids there was some actual information on their appearance and movement which I tried to follow as closely as possible, although I did not consider phospholipid saturation. With all individual components model and textured, I commenced the animating part, ATP synthase was animated to illustrate proton binding and release, inducing the rotary motion which acts as power supply for ATP synthesis. Protons were animated using a particle system, illustrating their chaotic movement and inability to travel through the membrane. Additionally, the co-enzymes were animated to illustrate the electron transport chain in accordance to each other. Finally, I did a voice over to explain the electron transport chain (ETC) and the effect of APA on the ETC. Moreover, I edited in some blurring and numbering to clarify what part of the animation I was talking about. Due to the used terminology and assumption of background knowledge, the animation can be challenging to understand for a layman. The 3D animation is shown below.
";

$lang['modeling title'] = "3D Modeling";
$lang['modeling text'] = "As a kid I have always been intruiged by computers and the new possibilities they offer when it comes art. Especially I was interested in the construction of 3D models as was done in animation and video games. Therefore, I started playing around with various 3D modeling- and sculpting applications like blender and 3ds max. Soon I realized, it would be a challenging hobby but far from impossible, thus, I started following various tutorials and even created some models from scratch. Additionally, I started combining this with drawing, which I often did when on holiday. Drawing my creations in multiple perspectives (e.g. from the front, side and top) allowed me to relatively easily construct them in 3D. My main interest at the time was modeling magical creatures, specifcally dragons. However, this is a rather challenging concept to properly develop in 3D, so a fully modelled, textured and rigged dragon is still on my to-do list. As is the case with many hobbies, it is very time consuming. Therefore, there are many projects I have been working on for a long time that still have to be finnished. However, during my last year of highschool, I figured I could incorporate this hobby into my final school project. Here, I modeled and animated the respiratory chain of a mitochondria under exposure of paracetamol, to illustrate some of its hepatotoxic effects on ATP synthesis.. Furthermore, I utilised this skillset during my bachelor programme at Maastricht University, where I modeled sculped a mosasaur for the Maastricht natural history museum, which we showcased as a hologram using the Pepper's ghost illusion technique.";


$lang['logo title'] = "Logo Design";
$lang['logo text'] = "During high school I would often draw and explore digital design using software like Adobe Illustrator, Photoshop and After Effects. Although, I never really focussed on this type of design, I got rather handy with the software and was therefore offered some opportunities to create logos for a few projects/departments of Maastricht University. One of which was from Phytome, a research financed by the European Commission to reduce nitrite, which are carcinogenic components, in red meat products to eliminate its cancer inducing properties. Additionally, I designed a logo for the Honours Programme of the Faculty of Health, Medicine and Life Sciences at Maastricht University, an additional curriculum for the elite students of the faculty. These logos, and a few more are illustrated in a slideshow below.";




$lang['TEXT2'] = ' It is a second text box';


 ?>